### ISSUE TITLE
[fix] 异常 read ECONNRESET

### ISSUE THREAD

**Issue by zzswang** [36node/32960#16]
## 需求 

会遇到如下的很多 socket 异常断开的读取错误

通过 模拟多客户端，不停的发送包，收到应答后，断开 tcp 连接。看看能否复现并修复这个bug

这应该是终端设备上来的，每次发起 tcp 连接，传输结束收到应答后会断开。

```
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:19.977884922Z { errno: 'ECONNRESET',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:19.977903742Z   code: 'ECONNRESET',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:19.977909375Z   syscall: 'read',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:19.977926742Z   session: 'LMuX_3s_ec',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:19.977929929Z   name: 'Error',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:19.977932937Z   message: 'read ECONNRESET',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:19.977935936Z   stack:
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:19.977938909Z    'Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)' }
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:19.978153203Z {"level":30,"time":1542964279977,"msg":"session closed","pid":15,"hostname":"2be29e25ea81-shanghaibus-v0-bus32960-3","session":"LMuX_3s_ec","v":1}
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.089226376Z { errno: 'ECONNRESET',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.089271722Z   code: 'ECONNRESET',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.089279574Z   syscall: 'read',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.089283977Z   session: 'ed6ebvhBw6',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.089288392Z   name: 'Error',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.089293359Z   message: 'read ECONNRESET',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.089297133Z   stack:
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.089300077Z    'Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)' }
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.089518826Z {"level":30,"time":1542964280089,"msg":"session closed","pid":15,"hostname":"2be29e25ea81-shanghaibus-v0-bus32960-3","session":"ed6ebvhBw6","v":1}
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.241210902Z { errno: 'ECONNRESET',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.241257597Z   code: 'ECONNRESET',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.241264874Z   syscall: 'read',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.241269523Z   session: 'e6tg9qmB20',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.241273653Z   name: 'Error',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.241283405Z   message: 'read ECONNRESET',
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.241287889Z   stack:
Shanghaibus-v0_bus32960_3 | 2018-11-23T09:11:20.241292104Z    'Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)' }
```

**Comment by 0neSe7en** [comment]
怀疑是由于客户端直接断开链接，而没有 `FIN`  导致的

**Comment by zzswang** [comment]
上面的第一条和第二条日志，很有意思。正好它们是同一个 session 的。

第一条日志报了一个 异常链接的错误

第二条日志是打印了一条 正常的 socket close 事件，是在 onclose 打印的。所以我在想是不是咱们这边还在读取什么东西？

**Comment by zzswang** [comment]
大厅没有同步
